### ISSUE TITLE
请教问题说明

### ISSUE THREAD

**Issue by zhufengreact** [zhufengreact/homework#1]
在这里用markdown语法编辑你的问题，**并把相应的步骤、报错信息、截图传上来。**方便其他同学遇到类似的问题。

谢谢大家配合。

`ps：多上github，下一个大牛就是你。`

**Comment by ning5129** [comment]
在全局环境下安装　　npm install babel-cli -g，和在项目文件目录下安装babel-with-cli，这两个有什么区别吗，在项目中是如何应用的, 如果单纯只解析react 文件，是不是只安装babel-with-react就可以了？

**Comment by simmonssimmons** [comment]
![image](https://user-images.githubusercontent.com/33974948/38558048-8bb0d1b0-3d01-11e8-8e26-f77bc692a2e7.png
请问老师，文件是在老师网站下载的，然后npm install安装，npm start;
问题一：react引入bootstrap以后，navbar里面Ul和Li没有左漂。我尝试了好几个版本bootstrap，也试了react-bootrap也是不行呢。必须自己写个css，才行，谢谢

**Comment by simmonssimmons** [comment]
![image](https://user-images.githubusercontent.com/33974948/38558604-392e9560-3d03-11e8-9def-7f0d37054c09.png)
![image](https://user-images.githubusercontent.com/33974948/38558624-4952f166-3d03-11e8-99a0-928d81838319.png)
问题二：请问宽度都是700多px呢，而且感觉显示明显偏大，跟老师讲课格式不一致呢，试了viewport没有效果，谢谢 问题多了点~
