### ISSUE TITLE
为何嵌套function就可以取到this

### ISSUE THREAD

**Issue by liushaohua** [zhufengreact/homework#17]
<form onSubmit={() => this.handleSubmit}>
RT为何需要()中才能取到this?

**Comment by GuoYongfeng** [comment]
直接写`this.handleSubmit`绑定在DOMElement上时，handleSubmit中的this会指向当前的DOMElement，使用`this.handleSubmit.bing(this)`的话可以让this指向当前组件，建议的写法是用箭头函数来写handleSubmit，这样可以很好的解决这个问题。
